package dev.kdrag0n.android12ext.core.monet.theme

// Color tables generated by ReferenceGenerator. Do not edit.
object ReferenceColors {
    object Dp3 {
        object SystemDefault : ColorScheme() {
            override val neutral1 = listOf(
                    0xffffff,
                    0xe2e2e2,
                    0xc6c6c6,
                    0xababab,
                    0x909090,
                    0x757575,
                    0x5e5e5e,
                    0x464646,
                    0x303030,
                    0x1b1b1b,
                    0x000000,
            )

            override val neutral2 = listOf(
                    0xffffff,
                    0xe2e2e2,
                    0xc6c6c6,
                    0xababab,
                    0x909090,
                    0x757575,
                    0x5e5e5e,
                    0x464646,
                    0x303030,
                    0x1b1b1b,
                    0x000000,
            )

            override val accent1 = listOf(
                    0xffffff,
                    0xd3e3fd,
                    0xa8c7fa,
                    0x7cacf8,
                    0x4c8df6,
                    0x1b6ef3,
                    0x0b57d0,
                    0x0842a0,
                    0x062e6f,
                    0x041e49,
                    0x000000,
            )

            override val accent2 = listOf(
                    0xffffff,
                    0xdfe0ff,
                    0xc3c4e2,
                    0xa8a9c6,
                    0x8d8fab,
                    0x72738f,
                    0x5a5c77,
                    0x43455e,
                    0x2c2f46,
                    0x161a30,
                    0x000000,
            )

            override val accent3 = listOf(
                    0xffffff,
                    0xf5d9ff,
                    0xd8bde6,
                    0xbca2ca,
                    0xa187ae,
                    0x846c91,
                    0x6d567a,
                    0x553e61,
                    0x3d2849,
                    0x271332,
                    0x000000,
            )
        }

        object MonetBlack : ColorScheme() {
            override val neutral1 = listOf(
                    0xffffff,
                    0xe4e2e1,
                    0xc8c6c5,
                    0xadabaa,
                    0x929090,
                    0x777675,
                    0x5f5e5e,
                    0x474646,
                    0x313030,
                    0x1c1b1b,
                    0x000000,
            )

            override val neutral2 = listOf(
                    0xffffff,
                    0xe4e2e1,
                    0xc8c6c5,
                    0xadabaa,
                    0x929090,
                    0x777675,
                    0x5f5e5e,
                    0x474646,
                    0x313030,
                    0x1c1b1b,
                    0x000000,
            )

            override val accent1 = listOf(
                    0xffffff,
                    0xe4e2e1,
                    0xc8c6c5,
                    0xadabaa,
                    0x929090,
                    0x777675,
                    0x5f5e5e,
                    0x474646,
                    0x313030,
                    0x1c1b1b,
                    0x000000,
            )

            override val accent2 = listOf(
                    0xffffff,
                    0xe4e2e1,
                    0xc8c6c5,
                    0xadabaa,
                    0x929090,
                    0x777675,
                    0x5f5e5e,
                    0x474646,
                    0x313030,
                    0x1c1b1b,
                    0x000000,
            )

            override val accent3 = listOf(
                    0xffffff,
                    0xe4e2e1,
                    0xc8c6c5,
                    0xadabaa,
                    0x929090,
                    0x777675,
                    0x5f5e5e,
                    0x474646,
                    0x313030,
                    0x1c1b1b,
                    0x000000,
            )
        }

        object MonetPurple : ColorScheme() {
            override val neutral1 = listOf(
                    0xffffff,
                    0xeedee8,
                    0xd1c2cc,
                    0xb5a7b1,
                    0x9a8d96,
                    0x7f737b,
                    0x675b64,
                    0x4b4549,
                    0x372e35,
                    0x211920,
                    0x000000,
            )

            override val neutral2 = listOf(
                    0xffffff,
                    0xe7e1e3,
                    0xccc4c9,
                    0xb1a9ad,
                    0x968f93,
                    0x7b7478,
                    0x635d60,
                    0x4b4549,
                    0x342f32,
                    0x1f1a1e,
                    0x000000,
            )

            override val accent1 = listOf(
                    0xffffff,
                    0xffd5ff,
                    0xfeabf3,
                    0xe090d5,
                    0xc376ba,
                    0xa55c9d,
                    0x8a4584,
                    0x6e2d6a,
                    0x541452,
                    0x380038,
                    0x000600,
            )

            override val accent2 = listOf(
                    0xffffff,
                    0xf7dbef,
                    0xd9bfd2,
                    0xbda4b6,
                    0xa28a9c,
                    0x866f81,
                    0x6d5868,
                    0x544150,
                    0x3c2b39,
                    0x271624,
                    0x000001,
            )

            override val accent3 = listOf(
                    0xffffff,
                    0xffdcc3,
                    0xffb59d,
                    0xe39982,
                    0xc57f6a,
                    0xa76552,
                    0x8a4e3c,
                    0x6e3727,
                    0x522213,
                    0x370e03,
                    0x000000,
            )
        }

        object MonetGreen : ColorScheme() {
            override val neutral1 = listOf(
                    0xffffff,
                    0xe2e3dc,
                    0xc3c8bb,
                    0xa8ada0,
                    0x8d9286,
                    0x73786c,
                    0x5b6055,
                    0x44483e,
                    0x2d3228,
                    0x181d14,
                    0x000000,
            )

            override val neutral2 = listOf(
                    0xffffff,
                    0xe2e3dc,
                    0xc6c7c0,
                    0xabaca5,
                    0x90918b,
                    0x767673,
                    0x5d5f59,
                    0x464742,
                    0x2f312c,
                    0x1b1c19,
                    0x000000,
            )

            override val accent1 = listOf(
                    0xffffff,
                    0xbff28f,
                    0xa4d575,
                    0x8ab95d,
                    0x719d46,
                    0x57822e,
                    0x406917,
                    0x2a5000,
                    0x163800,
                    0x042100,
                    0x000000,
            )

            override val accent2 = listOf(
                    0xffffff,
                    0xdae7c8,
                    0xbecbad,
                    0xa3b093,
                    0x8a947d,
                    0x6e7a60,
                    0x57624a,
                    0x3f4a34,
                    0x29341f,
                    0x151e0b,
                    0x000000,
            )

            override val accent3 = listOf(
                    0xffffff,
                    0xa6f0eb,
                    0x8bd3d0,
                    0x6fb8b4,
                    0x549c99,
                    0x38817e,
                    0x196966,
                    0x00504d,
                    0x003735,
                    0x00201e,
                    0x000203,
            )
        }
    }
}