package dev.kdrag0n.android12ext.monet.theme

import dev.kdrag0n.android12ext.monet.colors.Srgb

// Color tables generated by ReferenceGenerator. Do not edit.
object ReferenceColors {
    object Dp3 {
        object SystemDefault : ColorScheme() {
            override val neutral1 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xe2e2e2),
                    Srgb(0xc6c6c6),
                    Srgb(0xababab),
                    Srgb(0x909090),
                    Srgb(0x757575),
                    Srgb(0x5e5e5e),
                    Srgb(0x464646),
                    Srgb(0x303030),
                    Srgb(0x1b1b1b),
                    Srgb(0x000000),
            )

            override val neutral2 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xe2e2e2),
                    Srgb(0xc6c6c6),
                    Srgb(0xababab),
                    Srgb(0x909090),
                    Srgb(0x757575),
                    Srgb(0x5e5e5e),
                    Srgb(0x464646),
                    Srgb(0x303030),
                    Srgb(0x1b1b1b),
                    Srgb(0x000000),
            )

            override val accent1 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xd3e3fd),
                    Srgb(0xa8c7fa),
                    Srgb(0x7cacf8),
                    Srgb(0x4c8df6),
                    Srgb(0x1b6ef3),
                    Srgb(0x0b57d0),
                    Srgb(0x0842a0),
                    Srgb(0x062e6f),
                    Srgb(0x041e49),
                    Srgb(0x000000),
            )

            override val accent2 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xdfe0ff),
                    Srgb(0xc3c4e2),
                    Srgb(0xa8a9c6),
                    Srgb(0x8d8fab),
                    Srgb(0x72738f),
                    Srgb(0x5a5c77),
                    Srgb(0x43455e),
                    Srgb(0x2c2f46),
                    Srgb(0x161a30),
                    Srgb(0x000000),
            )

            override val accent3 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xf5d9ff),
                    Srgb(0xd8bde6),
                    Srgb(0xbca2ca),
                    Srgb(0xa187ae),
                    Srgb(0x846c91),
                    Srgb(0x6d567a),
                    Srgb(0x553e61),
                    Srgb(0x3d2849),
                    Srgb(0x271332),
                    Srgb(0x000000),
            )
        }

        object MonetBlack : ColorScheme() {
            override val neutral1 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xe4e2e1),
                    Srgb(0xc8c6c5),
                    Srgb(0xadabaa),
                    Srgb(0x929090),
                    Srgb(0x777675),
                    Srgb(0x5f5e5e),
                    Srgb(0x474646),
                    Srgb(0x313030),
                    Srgb(0x1c1b1b),
                    Srgb(0x000000),
            )

            override val neutral2 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xe4e2e1),
                    Srgb(0xc8c6c5),
                    Srgb(0xadabaa),
                    Srgb(0x929090),
                    Srgb(0x777675),
                    Srgb(0x5f5e5e),
                    Srgb(0x474646),
                    Srgb(0x313030),
                    Srgb(0x1c1b1b),
                    Srgb(0x000000),
            )

            override val accent1 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xe4e2e1),
                    Srgb(0xc8c6c5),
                    Srgb(0xadabaa),
                    Srgb(0x929090),
                    Srgb(0x777675),
                    Srgb(0x5f5e5e),
                    Srgb(0x474646),
                    Srgb(0x313030),
                    Srgb(0x1c1b1b),
                    Srgb(0x000000),
            )

            override val accent2 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xe4e2e1),
                    Srgb(0xc8c6c5),
                    Srgb(0xadabaa),
                    Srgb(0x929090),
                    Srgb(0x777675),
                    Srgb(0x5f5e5e),
                    Srgb(0x474646),
                    Srgb(0x313030),
                    Srgb(0x1c1b1b),
                    Srgb(0x000000),
            )

            override val accent3 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xe4e2e1),
                    Srgb(0xc8c6c5),
                    Srgb(0xadabaa),
                    Srgb(0x929090),
                    Srgb(0x777675),
                    Srgb(0x5f5e5e),
                    Srgb(0x474646),
                    Srgb(0x313030),
                    Srgb(0x1c1b1b),
                    Srgb(0x000000),
            )
        }

        object MonetPurple : ColorScheme() {
            override val neutral1 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xeedee8),
                    Srgb(0xd1c2cc),
                    Srgb(0xb5a7b1),
                    Srgb(0x9a8d96),
                    Srgb(0x7f737b),
                    Srgb(0x675b64),
                    Srgb(0x4b4549),
                    Srgb(0x372e35),
                    Srgb(0x211920),
                    Srgb(0x000000),
            )

            override val neutral2 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xe7e1e3),
                    Srgb(0xccc4c9),
                    Srgb(0xb1a9ad),
                    Srgb(0x968f93),
                    Srgb(0x7b7478),
                    Srgb(0x635d60),
                    Srgb(0x4b4549),
                    Srgb(0x342f32),
                    Srgb(0x1f1a1e),
                    Srgb(0x000000),
            )

            override val accent1 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xffd5ff),
                    Srgb(0xfeabf3),
                    Srgb(0xe090d5),
                    Srgb(0xc376ba),
                    Srgb(0xa55c9d),
                    Srgb(0x8a4584),
                    Srgb(0x6e2d6a),
                    Srgb(0x541452),
                    Srgb(0x380038),
                    Srgb(0x000600),
            )

            override val accent2 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xf7dbef),
                    Srgb(0xd9bfd2),
                    Srgb(0xbda4b6),
                    Srgb(0xa28a9c),
                    Srgb(0x866f81),
                    Srgb(0x6d5868),
                    Srgb(0x544150),
                    Srgb(0x3c2b39),
                    Srgb(0x271624),
                    Srgb(0x000001),
            )

            override val accent3 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xffdcc3),
                    Srgb(0xffb59d),
                    Srgb(0xe39982),
                    Srgb(0xc57f6a),
                    Srgb(0xa76552),
                    Srgb(0x8a4e3c),
                    Srgb(0x6e3727),
                    Srgb(0x522213),
                    Srgb(0x370e03),
                    Srgb(0x000000),
            )
        }

        object MonetGreen : ColorScheme() {
            override val neutral1 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xe2e3dc),
                    Srgb(0xc3c8bb),
                    Srgb(0xa8ada0),
                    Srgb(0x8d9286),
                    Srgb(0x73786c),
                    Srgb(0x5b6055),
                    Srgb(0x44483e),
                    Srgb(0x2d3228),
                    Srgb(0x181d14),
                    Srgb(0x000000),
            )

            override val neutral2 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xe2e3dc),
                    Srgb(0xc6c7c0),
                    Srgb(0xabaca5),
                    Srgb(0x90918b),
                    Srgb(0x767673),
                    Srgb(0x5d5f59),
                    Srgb(0x464742),
                    Srgb(0x2f312c),
                    Srgb(0x1b1c19),
                    Srgb(0x000000),
            )

            override val accent1 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xbff28f),
                    Srgb(0xa4d575),
                    Srgb(0x8ab95d),
                    Srgb(0x719d46),
                    Srgb(0x57822e),
                    Srgb(0x406917),
                    Srgb(0x2a5000),
                    Srgb(0x163800),
                    Srgb(0x042100),
                    Srgb(0x000000),
            )

            override val accent2 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xdae7c8),
                    Srgb(0xbecbad),
                    Srgb(0xa3b093),
                    Srgb(0x8a947d),
                    Srgb(0x6e7a60),
                    Srgb(0x57624a),
                    Srgb(0x3f4a34),
                    Srgb(0x29341f),
                    Srgb(0x151e0b),
                    Srgb(0x000000),
            )

            override val accent3 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xa6f0eb),
                    Srgb(0x8bd3d0),
                    Srgb(0x6fb8b4),
                    Srgb(0x549c99),
                    Srgb(0x38817e),
                    Srgb(0x196966),
                    Srgb(0x00504d),
                    Srgb(0x003735),
                    Srgb(0x00201e),
                    Srgb(0x000203),
            )
        }
    }

    object Beta1 {
        object PixelDefault : ColorScheme() {
            override val neutral1 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xe2e2e2),
                    Srgb(0xc6c6c6),
                    Srgb(0xababab),
                    Srgb(0x909090),
                    Srgb(0x757575),
                    Srgb(0x5e5e5e),
                    Srgb(0x464646),
                    Srgb(0x303030),
                    Srgb(0x1b1b1b),
                    Srgb(0x000000),
            )

            override val neutral2 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xe2e2e2),
                    Srgb(0xc6c6c6),
                    Srgb(0xababab),
                    Srgb(0x909090),
                    Srgb(0x757575),
                    Srgb(0x5e5e5e),
                    Srgb(0x464646),
                    Srgb(0x303030),
                    Srgb(0x1b1b1b),
                    Srgb(0x000000),
            )

            override val accent1 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xd3e3fd),
                    Srgb(0xa8c7fa),
                    Srgb(0x7cacf8),
                    Srgb(0x4c8df6),
                    Srgb(0x1b6ef3),
                    Srgb(0x0b57d0),
                    Srgb(0x0842a0),
                    Srgb(0x062e6f),
                    Srgb(0x041e49),
                    Srgb(0x000000),
            )

            override val accent2 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xdfe0ff),
                    Srgb(0xc3c4e2),
                    Srgb(0xa8a9c6),
                    Srgb(0x8d8fab),
                    Srgb(0x72738f),
                    Srgb(0x5a5c77),
                    Srgb(0x43455e),
                    Srgb(0x2c2f46),
                    Srgb(0x161a30),
                    Srgb(0x000000),
            )

            override val accent3 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xf5d9ff),
                    Srgb(0xd8bde6),
                    Srgb(0xbca2ca),
                    Srgb(0xa187ae),
                    Srgb(0x846c91),
                    Srgb(0x6d567a),
                    Srgb(0x553e61),
                    Srgb(0x3d2849),
                    Srgb(0x271332),
                    Srgb(0x000000),
            )

        }

        object AospDefault : ColorScheme() {
            override val neutral1 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xe2e2e2),
                    Srgb(0xc6c6c6),
                    Srgb(0xababab),
                    Srgb(0x909090),
                    Srgb(0x757575),
                    Srgb(0x5e5e5e),
                    Srgb(0x464646),
                    Srgb(0x303030),
                    Srgb(0x1b1b1b),
                    Srgb(0x000000),
            )

            override val neutral2 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xe2e2e2),
                    Srgb(0xc6c6c6),
                    Srgb(0xababab),
                    Srgb(0x909090),
                    Srgb(0x757575),
                    Srgb(0x5e5e5e),
                    Srgb(0x464646),
                    Srgb(0x303030),
                    Srgb(0x1b1b1b),
                    Srgb(0x000000),
            )

            override val accent1 = listOf(
                    Srgb(0xffffff),
                    Srgb(0x8df5e3),
                    Srgb(0x71d8c7),
                    Srgb(0x53bcac),
                    Srgb(0x34a192),
                    Srgb(0x008375),
                    Srgb(0x006c5f),
                    Srgb(0x005747),
                    Srgb(0x003e31),
                    Srgb(0x002214),
                    Srgb(0x000000),
            )

            override val accent2 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xbfebe3),
                    Srgb(0xa4cfc7),
                    Srgb(0x89b4ac),
                    Srgb(0x6f9991),
                    Srgb(0x537c75),
                    Srgb(0x3d665f),
                    Srgb(0x254e47),
                    Srgb(0x0c3731),
                    Srgb(0x00211c),
                    Srgb(0x000000),
            )

            override val accent3 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xecdbff),
                    Srgb(0xcfbfeb),
                    Srgb(0xb3a4cf),
                    Srgb(0x988ab3),
                    Srgb(0x7b6e96),
                    Srgb(0x64587f),
                    Srgb(0x4c4165),
                    Srgb(0x352b4d),
                    Srgb(0x1e1636),
                    Srgb(0x000000),
            )

        }

        object MonetMint : ColorScheme() {
            override val neutral1 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xdde4e0),
                    Srgb(0xbfc9c4),
                    Srgb(0xa5ada9),
                    Srgb(0x89938e),
                    Srgb(0x6f7874),
                    Srgb(0x57605c),
                    Srgb(0x404945),
                    Srgb(0x2a322f),
                    Srgb(0x151d1a),
                    Srgb(0x000000),
            )

            override val neutral2 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xe0e3e0),
                    Srgb(0xc4c7c4),
                    Srgb(0xa8acaa),
                    Srgb(0x8e928f),
                    Srgb(0x737774),
                    Srgb(0x5c5f5d),
                    Srgb(0x464746),
                    Srgb(0x2d312f),
                    Srgb(0x1a1c1b),
                    Srgb(0x000000),
            )

            override val accent1 = listOf(
                    Srgb(0xffffff),
                    Srgb(0x7ef8d4),
                    Srgb(0x60dbb9),
                    Srgb(0x3ebf9d),
                    Srgb(0x10a384),
                    Srgb(0x00866a),
                    Srgb(0x006c50),
                    Srgb(0x005139),
                    Srgb(0x003822),
                    Srgb(0x00210e),
                    Srgb(0x000200),
            )

            override val accent2 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xcce9dd),
                    Srgb(0xb0cdc1),
                    Srgb(0x96b1a7),
                    Srgb(0x7c968c),
                    Srgb(0x627c72),
                    Srgb(0x4a645b),
                    Srgb(0x334c43),
                    Srgb(0x1d352d),
                    Srgb(0x072019),
                    Srgb(0x000000),
            )

            override val accent3 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xd9e4ec),
                    Srgb(0x96ceed),
                    Srgb(0x7cb2d1),
                    Srgb(0x6197b5),
                    Srgb(0x457c99),
                    Srgb(0x2b6480),
                    Srgb(0x074c67),
                    Srgb(0x00344d),
                    Srgb(0x001d34),
                    Srgb(0x010000),
            )

        }

        object MonetPurple : ColorScheme() {
            override val neutral1 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xeddfe7),
                    Srgb(0xd0c3cb),
                    Srgb(0xb4a8b0),
                    Srgb(0x9a8d96),
                    Srgb(0x7b7478),
                    Srgb(0x665b63),
                    Srgb(0x4d444b),
                    Srgb(0x362e34),
                    Srgb(0x21191f),
                    Srgb(0x000000),
            )

            override val neutral2 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xe8e0e4),
                    Srgb(0xccc5c8),
                    Srgb(0xaeaaab),
                    Srgb(0x958f92),
                    Srgb(0x7a7477),
                    Srgb(0x625d60),
                    Srgb(0x4a4548),
                    Srgb(0x323031),
                    Srgb(0x1e1a1d),
                    Srgb(0x000000),
            )

            override val accent1 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xffd5ff),
                    Srgb(0xfeabf3),
                    Srgb(0xe090d6),
                    Srgb(0xc376ba),
                    Srgb(0xa55c9d),
                    Srgb(0x8a4584),
                    Srgb(0x6f2d6a),
                    Srgb(0x541452),
                    Srgb(0x380038),
                    Srgb(0x000600),
            )

            override val accent2 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xf5dbef),
                    Srgb(0xd9bfd3),
                    Srgb(0xbda4b7),
                    Srgb(0xa28a9d),
                    Srgb(0x866f82),
                    Srgb(0x6d5869),
                    Srgb(0x544151),
                    Srgb(0x3d2b3a),
                    Srgb(0x271625),
                    Srgb(0x000002),
            )

            override val accent3 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xffdcc3),
                    Srgb(0xffb59d),
                    Srgb(0xe39983),
                    Srgb(0xc57f6a),
                    Srgb(0xa66552),
                    Srgb(0x8a4f3c),
                    Srgb(0x6e3827),
                    Srgb(0x522213),
                    Srgb(0x370e03),
                    Srgb(0x000000),
            )

        }

        object MonetGreen : ColorScheme() {
            override val neutral1 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xe0e4d7),
                    Srgb(0xc3c8ba),
                    Srgb(0xa8ada0),
                    Srgb(0x8d9285),
                    Srgb(0x74776e),
                    Srgb(0x5d5f59),
                    Srgb(0x454840),
                    Srgb(0x2d3228),
                    Srgb(0x181d14),
                    Srgb(0x000000),
            )

            override val neutral2 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xe2e3db),
                    Srgb(0xc6c7c0),
                    Srgb(0xaaaca4),
                    Srgb(0x8f918a),
                    Srgb(0x767673),
                    Srgb(0x5d5f59),
                    Srgb(0x454842),
                    Srgb(0x30312e),
                    Srgb(0x1a1c18),
                    Srgb(0x000000),
            )

            override val accent1 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xbff28f),
                    Srgb(0xa3d576),
                    Srgb(0x89b95d),
                    Srgb(0x709d46),
                    Srgb(0x56822e),
                    Srgb(0x406918),
                    Srgb(0x295000),
                    Srgb(0x153800),
                    Srgb(0x082100),
                    Srgb(0x000000),
            )

            override val accent2 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xdae7c9),
                    Srgb(0xbecbad),
                    Srgb(0xa3af93),
                    Srgb(0x89957a),
                    Srgb(0x6e7a60),
                    Srgb(0x57624a),
                    Srgb(0x404a34),
                    Srgb(0x29331f),
                    Srgb(0x151e0c),
                    Srgb(0x000000),
            )

            override val accent3 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xa6f0ec),
                    Srgb(0x8bd3d0),
                    Srgb(0x6fb7b4),
                    Srgb(0x549c99),
                    Srgb(0x38817f),
                    Srgb(0x196966),
                    Srgb(0x00504e),
                    Srgb(0x003735),
                    Srgb(0x00201e),
                    Srgb(0x000204),
            )

        }

        object MonetOrange : ColorScheme() {
            override val neutral1 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xf2dfd2),
                    Srgb(0xd5c3b7),
                    Srgb(0xb9a89c),
                    Srgb(0x9e8e82),
                    Srgb(0x827369),
                    Srgb(0x645d58),
                    Srgb(0x51443b),
                    Srgb(0x3a2e26),
                    Srgb(0x221a14),
                    Srgb(0x000000),
            )

            override val neutral2 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xe8e1de),
                    Srgb(0xcfc4be),
                    Srgb(0xb3a9a3),
                    Srgb(0x988f89),
                    Srgb(0x7a7572),
                    Srgb(0x655d58),
                    Srgb(0x4d4541),
                    Srgb(0x32302f),
                    Srgb(0x201a16),
                    Srgb(0x000000),
            )

            override val accent1 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xffe086),
                    Srgb(0xffb962),
                    Srgb(0xee9744),
                    Srgb(0xce7e2d),
                    Srgb(0xae6411),
                    Srgb(0x8b500e),
                    Srgb(0x643e1b),
                    Srgb(0x4f2500),
                    Srgb(0x360f00),
                    Srgb(0x000000),
            )

            override val accent2 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xffdcc1),
                    Srgb(0xe2c0a6),
                    Srgb(0xc6a58c),
                    Srgb(0xa98b73),
                    Srgb(0x8d715a),
                    Srgb(0x735944),
                    Srgb(0x59422e),
                    Srgb(0x3d2d20),
                    Srgb(0x291707),
                    Srgb(0x000000),
            )

            override val accent3 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xdde9a0),
                    Srgb(0xc0cd87),
                    Srgb(0xa5b16e),
                    Srgb(0x8b9656),
                    Srgb(0x707b3e),
                    Srgb(0x596329),
                    Srgb(0x424b14),
                    Srgb(0x2c3400),
                    Srgb(0x181e00),
                    Srgb(0x000000),
            )

        }

        object MonetTeal : ColorScheme() {
            override val neutral1 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xdbe4e8),
                    Srgb(0xbfc8cc),
                    Srgb(0xa6acaf),
                    Srgb(0x899296),
                    Srgb(0x6e777b),
                    Srgb(0x576063),
                    Srgb(0x40484c),
                    Srgb(0x293235),
                    Srgb(0x151d20),
                    Srgb(0x000001),
            )

            override val neutral2 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xe1e3e4),
                    Srgb(0xc5c7c8),
                    Srgb(0xaaabac),
                    Srgb(0x8f9192),
                    Srgb(0x747677),
                    Srgb(0x5d5f60),
                    Srgb(0x454748),
                    Srgb(0x2f3132),
                    Srgb(0x191c1d),
                    Srgb(0x000000),
            )

            override val accent1 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xdae4e9),
                    Srgb(0x6fd3f7),
                    Srgb(0x51b7db),
                    Srgb(0x2e9cbf),
                    Srgb(0x0080a2),
                    Srgb(0x006687),
                    Srgb(0x004c6b),
                    Srgb(0x003352),
                    Srgb(0x001b3c),
                    Srgb(0x010000),
            )

            override val accent2 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xcfe6f2),
                    Srgb(0xb3cad5),
                    Srgb(0x98afb9),
                    Srgb(0x7e949f),
                    Srgb(0x647983),
                    Srgb(0x4c626b),
                    Srgb(0x354a53),
                    Srgb(0x1e333c),
                    Srgb(0x081e26),
                    Srgb(0x000005),
            )

            override val accent3 = listOf(
                    Srgb(0xffffff),
                    Srgb(0xdee0ff),
                    Srgb(0xc0c2fa),
                    Srgb(0xa4a7dd),
                    Srgb(0x8a8dc1),
                    Srgb(0x6f72a4),
                    Srgb(0x575a8b),
                    Srgb(0x404371),
                    Srgb(0x292c59),
                    Srgb(0x141643),
                    Srgb(0x000100),
            )

        }
    }
}