package dev.kdrag0n.android12ext.monet.theme

import dev.kdrag0n.android12ext.monet.colors.Srgb

// Color tables generated by ReferenceGenerator. Do not edit.
object ReferenceColors {
    object Beta1 {
        object PixelDefault : ColorScheme() {
            override val neutral1 = mapOf(
                0    to Srgb(0xffffff),
                50   to Srgb(0xf0f0f0),
                100  to Srgb(0xe2e2e2),
                200  to Srgb(0xc6c6c6),
                300  to Srgb(0xababab),
                400  to Srgb(0x909090),
                500  to Srgb(0x757575),
                600  to Srgb(0x5e5e5e),
                700  to Srgb(0x464646),
                800  to Srgb(0x303030),
                900  to Srgb(0x1b1b1b),
                1000 to Srgb(0x000000),
            )

            override val neutral2 = mapOf(
                0    to Srgb(0xffffff),
                50   to Srgb(0xf0f0f0),
                100  to Srgb(0xe2e2e2),
                200  to Srgb(0xc6c6c6),
                300  to Srgb(0xababab),
                400  to Srgb(0x909090),
                500  to Srgb(0x757575),
                600  to Srgb(0x5e5e5e),
                700  to Srgb(0x464646),
                800  to Srgb(0x303030),
                900  to Srgb(0x1b1b1b),
                1000 to Srgb(0x000000),
            )

            override val accent1 = mapOf(
                0    to Srgb(0xffffff),
                50   to Srgb(0xecf3fe),
                100  to Srgb(0xd3e3fd),
                200  to Srgb(0xa8c7fa),
                300  to Srgb(0x7cacf8),
                400  to Srgb(0x4c8df6),
                500  to Srgb(0x1b6ef3),
                600  to Srgb(0x0b57d0),
                700  to Srgb(0x0842a0),
                800  to Srgb(0x062e6f),
                900  to Srgb(0x041e49),
                1000 to Srgb(0x000000),
            )

            override val accent2 = mapOf(
                0    to Srgb(0xffffff),
                50   to Srgb(0xedeeff),
                100  to Srgb(0xdfe0ff),
                200  to Srgb(0xc3c4e2),
                300  to Srgb(0xa8a9c6),
                400  to Srgb(0x8d8fab),
                500  to Srgb(0x72738f),
                600  to Srgb(0x5a5c77),
                700  to Srgb(0x43455e),
                800  to Srgb(0x2c2f46),
                900  to Srgb(0x161a30),
                1000 to Srgb(0x000000),
            )

            override val accent3 = mapOf(
                0    to Srgb(0xffffff),
                50   to Srgb(0xffe7ff),
                100  to Srgb(0xf5d9ff),
                200  to Srgb(0xd8bde6),
                300  to Srgb(0xbca2ca),
                400  to Srgb(0xa187ae),
                500  to Srgb(0x846c91),
                600  to Srgb(0x6d567a),
                700  to Srgb(0x553e61),
                800  to Srgb(0x3d2849),
                900  to Srgb(0x271332),
                1000 to Srgb(0x000000),
            )

        }

        object AospDefault : ColorScheme() {
            override val neutral1 = mapOf(
                0    to Srgb(0xffffff),
                50   to Srgb(0xf0f0f0),
                100  to Srgb(0xe2e2e2),
                200  to Srgb(0xc6c6c6),
                300  to Srgb(0xababab),
                400  to Srgb(0x909090),
                500  to Srgb(0x757575),
                600  to Srgb(0x5e5e5e),
                700  to Srgb(0x464646),
                800  to Srgb(0x303030),
                900  to Srgb(0x1b1b1b),
                1000 to Srgb(0x000000),
            )

            override val neutral2 = mapOf(
                0    to Srgb(0xffffff),
                50   to Srgb(0xf0f0f0),
                100  to Srgb(0xe2e2e2),
                200  to Srgb(0xc6c6c6),
                300  to Srgb(0xababab),
                400  to Srgb(0x909090),
                500  to Srgb(0x757575),
                600  to Srgb(0x5e5e5e),
                700  to Srgb(0x464646),
                800  to Srgb(0x303030),
                900  to Srgb(0x1b1b1b),
                1000 to Srgb(0x000000),
            )

            override val accent1 = mapOf(
                0    to Srgb(0xffffff),
                50   to Srgb(0x9cfff2),
                100  to Srgb(0x8df5e3),
                200  to Srgb(0x71d8c7),
                300  to Srgb(0x53bcac),
                400  to Srgb(0x34a192),
                500  to Srgb(0x008375),
                600  to Srgb(0x006c5f),
                700  to Srgb(0x005747),
                800  to Srgb(0x003e31),
                900  to Srgb(0x002214),
                1000 to Srgb(0x000000),
            )

            override val accent2 = mapOf(
                0    to Srgb(0xffffff),
                50   to Srgb(0xcdfaf1),
                100  to Srgb(0xbfebe3),
                200  to Srgb(0xa4cfc7),
                300  to Srgb(0x89b4ac),
                400  to Srgb(0x6f9991),
                500  to Srgb(0x537c75),
                600  to Srgb(0x3d665f),
                700  to Srgb(0x254e47),
                800  to Srgb(0x0c3731),
                900  to Srgb(0x00211c),
                1000 to Srgb(0x000000),
            )

            override val accent3 = mapOf(
                0    to Srgb(0xffffff),
                50   to Srgb(0xf9eaff),
                100  to Srgb(0xecdbff),
                200  to Srgb(0xcfbfeb),
                300  to Srgb(0xb3a4cf),
                400  to Srgb(0x988ab3),
                500  to Srgb(0x7b6e96),
                600  to Srgb(0x64587f),
                700  to Srgb(0x4c4165),
                800  to Srgb(0x352b4d),
                900  to Srgb(0x1e1636),
                1000 to Srgb(0x000000),
            )

        }

        object MonetBlue : ColorScheme() {
            override val neutral1 = mapOf(
                0    to Srgb(0xffffff),
                50   to Srgb(0xeff0fb),
                100  to Srgb(0xe0e2ed),
                200  to Srgb(0xc4c6d1),
                300  to Srgb(0xa9abb5),
                400  to Srgb(0x8f909b),
                500  to Srgb(0x74767f),
                600  to Srgb(0x5c5e67),
                700  to Srgb(0x44464f),
                800  to Srgb(0x2e3039),
                900  to Srgb(0x191b23),
                1000 to Srgb(0x000002),
            )

            override val neutral2 = mapOf(
                0    to Srgb(0xffffff),
                50   to Srgb(0xf2f0f2),
                100  to Srgb(0xe2e2e6),
                200  to Srgb(0xc6c6ca),
                300  to Srgb(0xababaf),
                400  to Srgb(0x909094),
                500  to Srgb(0x767678),
                600  to Srgb(0x5e5e62),
                700  to Srgb(0x46464a),
                800  to Srgb(0x303034),
                900  to Srgb(0x1b1b1e),
                1000 to Srgb(0x000000),
            )

            override val accent1 = mapOf(
                0    to Srgb(0xffffff),
                50   to Srgb(0xcff8ff),
                100  to Srgb(0xbfe9ff),
                200  to Srgb(0xa2c9ff),
                300  to Srgb(0x81abfb),
                400  to Srgb(0x6690df),
                500  to Srgb(0x4a75c2),
                600  to Srgb(0x305da7),
                700  to Srgb(0x0d458e),
                800  to Srgb(0x002c71),
                900  to Srgb(0x000e5e),
                1000 to Srgb(0x000000),
            )

            override val accent2 = mapOf(
                0    to Srgb(0xffffff),
                50   to Srgb(0xeaf1ff),
                100  to Srgb(0xd9e3f9),
                200  to Srgb(0xbdc7dc),
                300  to Srgb(0xa2abc0),
                400  to Srgb(0x8891a5),
                500  to Srgb(0x6d768a),
                600  to Srgb(0x565e71),
                700  to Srgb(0x3e4758),
                800  to Srgb(0x283141),
                900  to Srgb(0x131c2b),
                1000 to Srgb(0x00000a),
            )

            override val accent3 = mapOf(
                0    to Srgb(0xffffff),
                50   to Srgb(0xffebff),
                100  to Srgb(0xffd5ff),
                200  to Srgb(0xe4b8e9),
                300  to Srgb(0xc89dcc),
                400  to Srgb(0xac83b1),
                500  to Srgb(0x8f6994),
                600  to Srgb(0x76517b),
                700  to Srgb(0x5d3a62),
                800  to Srgb(0x44244a),
                900  to Srgb(0x2d0e34),
                1000 to Srgb(0x030013),
            )

        }

        object MonetPurple : ColorScheme() {
            override val neutral1 = mapOf(
                0    to Srgb(0xffffff),
                50   to Srgb(0xf5eefa),
                100  to Srgb(0xe7e0eb),
                200  to Srgb(0xcac4cf),
                300  to Srgb(0xafa9b3),
                400  to Srgb(0x948f99),
                500  to Srgb(0x787579),
                600  to Srgb(0x615d66),
                700  to Srgb(0x49454e),
                800  to Srgb(0x322f37),
                900  to Srgb(0x1d1a22),
                1000 to Srgb(0x000001),
            )

            override val neutral2 = mapOf(
                0    to Srgb(0xffffff),
                50   to Srgb(0xf4f0f2),
                100  to Srgb(0xe5e1e4),
                200  to Srgb(0xc9c5c8),
                300  to Srgb(0xaeaaad),
                400  to Srgb(0x929092),
                500  to Srgb(0x787577),
                600  to Srgb(0x605e60),
                700  to Srgb(0x484648),
                800  to Srgb(0x313031),
                900  to Srgb(0x1c1b1d),
                1000 to Srgb(0x000000),
            )

            override val accent1 = mapOf(
                0    to Srgb(0xffffff),
                50   to Srgb(0xffebff),
                100  to Srgb(0xf7d8ff),
                200  to Srgb(0xd6baff),
                300  to Srgb(0xba9cf6),
                400  to Srgb(0x9e81d9),
                500  to Srgb(0x8367bc),
                600  to Srgb(0x6b4fa2),
                700  to Srgb(0x523688),
                800  to Srgb(0x3b1d70),
                900  to Srgb(0x25005a),
                1000 to Srgb(0x000000),
            )

            override val accent2 = mapOf(
                0    to Srgb(0xffffff),
                50   to Srgb(0xf7edff),
                100  to Srgb(0xe8dff3),
                200  to Srgb(0xccc3d7),
                300  to Srgb(0xb0a8ba),
                400  to Srgb(0x958e9f),
                500  to Srgb(0x7a7385),
                600  to Srgb(0x625c6c),
                700  to Srgb(0x4a4454),
                800  to Srgb(0x332e3c),
                900  to Srgb(0x1e1927),
                1000 to Srgb(0x000004),
            )

            override val accent3 = mapOf(
                0    to Srgb(0xffffff),
                50   to Srgb(0xffebfb),
                100  to Srgb(0xffd8ec),
                200  to Srgb(0xfdb2c5),
                300  to Srgb(0xdf97aa),
                400  to Srgb(0xc17d90),
                500  to Srgb(0xa36375),
                600  to Srgb(0x884c5d),
                700  to Srgb(0x6c3646),
                800  to Srgb(0x512030),
                900  to Srgb(0x370b1b),
                1000 to Srgb(0x000000),
            )

        }

        object MonetGreen : ColorScheme() {
            override val neutral1 = mapOf(
                0    to Srgb(0xffffff),
                50   to Srgb(0xebf3ea),
                100  to Srgb(0xdce5db),
                200  to Srgb(0xc2c8c1),
                300  to Srgb(0xa5ada5),
                400  to Srgb(0x8b938b),
                500  to Srgb(0x747773),
                600  to Srgb(0x5a605a),
                700  to Srgb(0x414942),
                800  to Srgb(0x2b322c),
                900  to Srgb(0x181d19),
                1000 to Srgb(0x000000),
            )

            override val neutral2 = mapOf(
                0    to Srgb(0xffffff),
                50   to Srgb(0xeff1ed),
                100  to Srgb(0xe1e3df),
                200  to Srgb(0xc5c7c3),
                300  to Srgb(0xa9aca8),
                400  to Srgb(0x8f928d),
                500  to Srgb(0x747773),
                600  to Srgb(0x5c5f5c),
                700  to Srgb(0x444844),
                800  to Srgb(0x2e312e),
                900  to Srgb(0x191c1a),
                1000 to Srgb(0x000000),
            )

            override val accent1 = mapOf(
                0    to Srgb(0xffffff),
                50   to Srgb(0xc0ffd7),
                100  to Srgb(0x98f7b5),
                200  to Srgb(0x7cda9a),
                300  to Srgb(0x61be81),
                400  to Srgb(0x45a268),
                500  to Srgb(0x268650),
                600  to Srgb(0x006d3a),
                700  to Srgb(0x005226),
                800  to Srgb(0x003910),
                900  to Srgb(0x002200),
                1000 to Srgb(0x000000),
            )

            override val accent2 = mapOf(
                0    to Srgb(0xffffff),
                50   to Srgb(0xdff7e2),
                100  to Srgb(0xd3e8d5),
                200  to Srgb(0xb6ccb9),
                300  to Srgb(0x9db0a0),
                400  to Srgb(0x819685),
                500  to Srgb(0x677b6b),
                600  to Srgb(0x506354),
                700  to Srgb(0x384b3d),
                800  to Srgb(0x223427),
                900  to Srgb(0x0e1f13),
                1000 to Srgb(0x000000),
            )

            override val accent3 = mapOf(
                0    to Srgb(0xffffff),
                50   to Srgb(0xd7f6ff),
                100  to Srgb(0xaaedff),
                200  to Srgb(0x8fd1e2),
                300  to Srgb(0x73b5c6),
                400  to Srgb(0x589aaa),
                500  to Srgb(0x3c7f8e),
                600  to Srgb(0x1e6776),
                700  to Srgb(0x004e5d),
                800  to Srgb(0x003543),
                900  to Srgb(0x001e2c),
                1000 to Srgb(0x020100),
            )

        }

        object MonetOrange : ColorScheme() {
            override val neutral1 = mapOf(
                0    to Srgb(0xffffff),
                50   to Srgb(0xfdeee4),
                100  to Srgb(0xf2dfd1),
                200  to Srgb(0xd5c3b6),
                300  to Srgb(0xb6a99f),
                400  to Srgb(0x9e8e81),
                500  to Srgb(0x827368),
                600  to Srgb(0x695c51),
                700  to Srgb(0x51443a),
                800  to Srgb(0x392e25),
                900  to Srgb(0x221a14),
                1000 to Srgb(0x000000),
            )

            override val neutral2 = mapOf(
                0    to Srgb(0xffffff),
                50   to Srgb(0xf6f0ec),
                100  to Srgb(0xe7e1de),
                200  to Srgb(0xcbc5c2),
                300  to Srgb(0xafaaa7),
                400  to Srgb(0x94908d),
                500  to Srgb(0x797573),
                600  to Srgb(0x615e5b),
                700  to Srgb(0x4a4644),
                800  to Srgb(0x33302e),
                900  to Srgb(0x1d1b1a),
                1000 to Srgb(0x000000),
            )

            override val accent1 = mapOf(
                0    to Srgb(0xffffff),
                50   to Srgb(0xfff1b8),
                100  to Srgb(0xffe081),
                200  to Srgb(0xffb95c),
                300  to Srgb(0xeb993f),
                400  to Srgb(0xcc7f27),
                500  to Srgb(0xac6508),
                600  to Srgb(0x8b5002),
                700  to Srgb(0x693c01),
                800  to Srgb(0x532200),
                900  to Srgb(0x360f00),
                1000 to Srgb(0x000000),
            )

            override val accent2 = mapOf(
                0    to Srgb(0xffffff),
                50   to Srgb(0xffefd2),
                100  to Srgb(0xfdddc1),
                200  to Srgb(0xe0c1a6),
                300  to Srgb(0xc3a68c),
                400  to Srgb(0xa78c73),
                500  to Srgb(0x8a715a),
                600  to Srgb(0x715a44),
                700  to Srgb(0x58432e),
                800  to Srgb(0x3e2d1d),
                900  to Srgb(0x281807),
                1000 to Srgb(0x000000),
            )

            override val accent3 = mapOf(
                0    to Srgb(0xffffff),
                50   to Srgb(0xe6f9b0),
                100  to Srgb(0xd8eaa3),
                200  to Srgb(0xbcce89),
                300  to Srgb(0xa1b271),
                400  to Srgb(0x879759),
                500  to Srgb(0x6d7c41),
                600  to Srgb(0x55642c),
                700  to Srgb(0x3e4c16),
                800  to Srgb(0x283502),
                900  to Srgb(0x151f00),
                1000 to Srgb(0x000000),
            )

        }

        object MonetTeal : ColorScheme() {
            override val neutral1 = mapOf(
                0    to Srgb(0xffffff),
                50   to Srgb(0xe8f3f0),
                100  to Srgb(0xd9e5e1),
                200  to Srgb(0xbdc9c5),
                300  to Srgb(0xa8acaa),
                400  to Srgb(0x889390),
                500  to Srgb(0x6e7876),
                600  to Srgb(0x56615e),
                700  to Srgb(0x3e4946),
                800  to Srgb(0x293230),
                900  to Srgb(0x141d1b),
                1000 to Srgb(0x000000),
            )

            override val neutral2 = mapOf(
                0    to Srgb(0xffffff),
                50   to Srgb(0xeff1f0),
                100  to Srgb(0xe0e3e2),
                200  to Srgb(0xc4c7c6),
                300  to Srgb(0xa8acaa),
                400  to Srgb(0x8d9190),
                500  to Srgb(0x737776),
                600  to Srgb(0x5c5f5e),
                700  to Srgb(0x434747),
                800  to Srgb(0x2e3130),
                900  to Srgb(0x191c1c),
                1000 to Srgb(0x000000),
            )

            override val accent1 = mapOf(
                0    to Srgb(0xffffff),
                50   to Srgb(0xa4ffff),
                100  to Srgb(0x83f6e3),
                200  to Srgb(0x66d9c7),
                300  to Srgb(0x47bdac),
                400  to Srgb(0x1fa291),
                500  to Srgb(0x008576),
                600  to Srgb(0x006b5c),
                700  to Srgb(0x005144),
                800  to Srgb(0x00382c),
                900  to Srgb(0x002117),
                1000 to Srgb(0x000301),
            )

            override val accent2 = mapOf(
                0    to Srgb(0xffffff),
                50   to Srgb(0xddf6f0),
                100  to Srgb(0xcfe8e2),
                200  to Srgb(0xb3ccc6),
                300  to Srgb(0x99b0ab),
                400  to Srgb(0x7e9691),
                500  to Srgb(0x647b76),
                600  to Srgb(0x50625e),
                700  to Srgb(0x354b46),
                800  to Srgb(0x203431),
                900  to Srgb(0x0a1f1c),
                1000 to Srgb(0x000000),
            )

            override val accent3 = mapOf(
                0    to Srgb(0xffffff),
                50   to Srgb(0xcbf9ff),
                100  to Srgb(0xbde9ff),
                200  to Srgb(0x9eccf3),
                300  to Srgb(0x83b0d6),
                400  to Srgb(0x6895ba),
                500  to Srgb(0x4d7a9e),
                600  to Srgb(0x346284),
                700  to Srgb(0x184b6b),
                800  to Srgb(0x003353),
                900  to Srgb(0x001c39),
                1000 to Srgb(0x000000),
            )

        }
    }

    object Beta2 {
        object PixelDefault : ColorScheme() {
            override val neutral1 = mapOf(
                0    to Srgb(0xffffff),
                10   to Srgb(0xfbfbfb),
                50   to Srgb(0xf0f0f0),
                100  to Srgb(0xe2e2e2),
                200  to Srgb(0xc6c6c6),
                300  to Srgb(0xababab),
                400  to Srgb(0x909090),
                500  to Srgb(0x757575),
                600  to Srgb(0x5e5e5e),
                700  to Srgb(0x464646),
                800  to Srgb(0x303030),
                900  to Srgb(0x1b1b1b),
                1000 to Srgb(0x000000),
            )

            override val neutral2 = mapOf(
                0    to Srgb(0xffffff),
                10   to Srgb(0xfbfbfb),
                50   to Srgb(0xf0f0f0),
                100  to Srgb(0xe2e2e2),
                200  to Srgb(0xc6c6c6),
                300  to Srgb(0xababab),
                400  to Srgb(0x909090),
                500  to Srgb(0x757575),
                600  to Srgb(0x5e5e5e),
                700  to Srgb(0x464646),
                800  to Srgb(0x303030),
                900  to Srgb(0x1b1b1b),
                1000 to Srgb(0x000000),
            )

            override val accent1 = mapOf(
                0    to Srgb(0xffffff),
                10   to Srgb(0xfdfcff),
                50   to Srgb(0xecf3fe),
                100  to Srgb(0xd3e3fd),
                200  to Srgb(0xa8c7fa),
                300  to Srgb(0x7cacf8),
                400  to Srgb(0x4c8df6),
                500  to Srgb(0x1b6ef3),
                600  to Srgb(0x0b57d0),
                700  to Srgb(0x0842a0),
                800  to Srgb(0x062e6f),
                900  to Srgb(0x041e49),
                1000 to Srgb(0x000000),
            )

            override val accent2 = mapOf(
                0    to Srgb(0xffffff),
                10   to Srgb(0xfdfbff),
                50   to Srgb(0xedeeff),
                100  to Srgb(0xdfe0ff),
                200  to Srgb(0xc3c4e2),
                300  to Srgb(0xa8a9c6),
                400  to Srgb(0x8d8fab),
                500  to Srgb(0x72738f),
                600  to Srgb(0x5a5c77),
                700  to Srgb(0x43455e),
                800  to Srgb(0x2c2f46),
                900  to Srgb(0x161a30),
                1000 to Srgb(0x000000),
            )

            override val accent3 = mapOf(
                0    to Srgb(0xffffff),
                10   to Srgb(0xfffbfd),
                50   to Srgb(0xffe7ff),
                100  to Srgb(0xf5d9ff),
                200  to Srgb(0xd8bde6),
                300  to Srgb(0xbca2ca),
                400  to Srgb(0xa187ae),
                500  to Srgb(0x846c91),
                600  to Srgb(0x6d567a),
                700  to Srgb(0x553e61),
                800  to Srgb(0x3d2849),
                900  to Srgb(0x271332),
                1000 to Srgb(0x000000),
            )

        }

        object AospDefault : ColorScheme() {
            override val neutral1 = mapOf(
                0    to Srgb(0xffffff),
                10   to Srgb(0xfbfbfb),
                50   to Srgb(0xf0f0f0),
                100  to Srgb(0xe2e2e2),
                200  to Srgb(0xc6c6c6),
                300  to Srgb(0xababab),
                400  to Srgb(0x909090),
                500  to Srgb(0x757575),
                600  to Srgb(0x5e5e5e),
                700  to Srgb(0x464646),
                800  to Srgb(0x303030),
                900  to Srgb(0x1b1b1b),
                1000 to Srgb(0x000000),
            )

            override val neutral2 = mapOf(
                0    to Srgb(0xffffff),
                10   to Srgb(0xfbfbfb),
                50   to Srgb(0xf0f0f0),
                100  to Srgb(0xe2e2e2),
                200  to Srgb(0xc6c6c6),
                300  to Srgb(0xababab),
                400  to Srgb(0x909090),
                500  to Srgb(0x757575),
                600  to Srgb(0x5e5e5e),
                700  to Srgb(0x464646),
                800  to Srgb(0x303030),
                900  to Srgb(0x1b1b1b),
                1000 to Srgb(0x000000),
            )

            override val accent1 = mapOf(
                0    to Srgb(0xffffff),
                10   to Srgb(0xf1fffc),
                50   to Srgb(0x9cfff2),
                100  to Srgb(0x8df5e3),
                200  to Srgb(0x71d8c7),
                300  to Srgb(0x53bcac),
                400  to Srgb(0x34a192),
                500  to Srgb(0x008375),
                600  to Srgb(0x006c5f),
                700  to Srgb(0x005747),
                800  to Srgb(0x003e31),
                900  to Srgb(0x002214),
                1000 to Srgb(0x000000),
            )

            override val accent2 = mapOf(
                0    to Srgb(0xffffff),
                10   to Srgb(0xf0fffc),
                50   to Srgb(0xcdfaf1),
                100  to Srgb(0xbfebe3),
                200  to Srgb(0xa4cfc7),
                300  to Srgb(0x89b4ac),
                400  to Srgb(0x6f9991),
                500  to Srgb(0x537c75),
                600  to Srgb(0x3d665f),
                700  to Srgb(0x254e47),
                800  to Srgb(0x0c3731),
                900  to Srgb(0x00211c),
                1000 to Srgb(0x000000),
            )

            override val accent3 = mapOf(
                0    to Srgb(0xffffff),
                10   to Srgb(0xfffbff),
                50   to Srgb(0xf9eaff),
                100  to Srgb(0xecdbff),
                200  to Srgb(0xcfbfeb),
                300  to Srgb(0xb3a4cf),
                400  to Srgb(0x988ab3),
                500  to Srgb(0x7b6e96),
                600  to Srgb(0x64587f),
                700  to Srgb(0x4c4165),
                800  to Srgb(0x352b4d),
                900  to Srgb(0x1e1636),
                1000 to Srgb(0x000000),
            )

        }

        object MonetBlue : ColorScheme() {
            override val neutral1 = mapOf(
                0    to Srgb(0xffffff),
                10   to Srgb(0xfdfbff),
                50   to Srgb(0xf2f0f4),
                100  to Srgb(0xe3e2e6),
                200  to Srgb(0xc7c6ca),
                300  to Srgb(0xababaf),
                400  to Srgb(0x919094),
                500  to Srgb(0x767579),
                600  to Srgb(0x5e5e61),
                700  to Srgb(0x46474a),
                800  to Srgb(0x303033),
                900  to Srgb(0x1b1b1d),
                1000 to Srgb(0x000000),
            )

            override val neutral2 = mapOf(
                0    to Srgb(0xffffff),
                10   to Srgb(0xfdfbff),
                50   to Srgb(0xeff0fa),
                100  to Srgb(0xe0e2ec),
                200  to Srgb(0xc4c6d0),
                300  to Srgb(0xa9abb4),
                400  to Srgb(0x8e919a),
                500  to Srgb(0x73767e),
                600  to Srgb(0x5c5e66),
                700  to Srgb(0x44464e),
                800  to Srgb(0x2e3038),
                900  to Srgb(0x191b22),
                1000 to Srgb(0x000000),
            )

            override val accent1 = mapOf(
                0    to Srgb(0xffffff),
                10   to Srgb(0xfdfbff),
                50   to Srgb(0xebf0ff),
                100  to Srgb(0xd6e2ff),
                200  to Srgb(0xacc7ff),
                300  to Srgb(0x82abfb),
                400  to Srgb(0x6790de),
                500  to Srgb(0x4b75c2),
                600  to Srgb(0x305da8),
                700  to Srgb(0x0e448f),
                800  to Srgb(0x002e6c),
                900  to Srgb(0x001a43),
                1000 to Srgb(0x000000),
            )

            override val accent2 = mapOf(
                0    to Srgb(0xffffff),
                10   to Srgb(0xfdfbff),
                50   to Srgb(0xebf0ff),
                100  to Srgb(0xdbe2f9),
                200  to Srgb(0xbfc6dd),
                300  to Srgb(0xa4abc1),
                400  to Srgb(0x8990a5),
                500  to Srgb(0x6e768a),
                600  to Srgb(0x575e71),
                700  to Srgb(0x3f4759),
                800  to Srgb(0x293042),
                900  to Srgb(0x141b2b),
                1000 to Srgb(0x000000),
            )

            override val accent3 = mapOf(
                0    to Srgb(0xffffff),
                10   to Srgb(0xfffbfb),
                50   to Srgb(0xffeaff),
                100  to Srgb(0xffd5ff),
                200  to Srgb(0xe6b8e9),
                300  to Srgb(0xc99ccd),
                400  to Srgb(0xad83b1),
                500  to Srgb(0x906895),
                600  to Srgb(0x76517c),
                700  to Srgb(0x5d3a63),
                800  to Srgb(0x45234b),
                900  to Srgb(0x2e0d35),
                1000 to Srgb(0x000000),
            )

        }

        object MonetPurple : ColorScheme() {
            override val neutral1 = mapOf(
                0    to Srgb(0xffffff),
                10   to Srgb(0xfffbfd),
                50   to Srgb(0xf4eff4),
                100  to Srgb(0xe6e1e5),
                200  to Srgb(0xc9c5c9),
                300  to Srgb(0xaeaaae),
                400  to Srgb(0x938f94),
                500  to Srgb(0x787579),
                600  to Srgb(0x615d62),
                700  to Srgb(0x484649),
                800  to Srgb(0x322f33),
                900  to Srgb(0x1c1b1e),
                1000 to Srgb(0x000000),
            )

            override val neutral2 = mapOf(
                0    to Srgb(0xffffff),
                10   to Srgb(0xfffbfd),
                50   to Srgb(0xf6eefa),
                100  to Srgb(0xe7e0ec),
                200  to Srgb(0xcac4cf),
                300  to Srgb(0xafa9b4),
                400  to Srgb(0x948e99),
                500  to Srgb(0x79747e),
                600  to Srgb(0x615c66),
                700  to Srgb(0x4a454f),
                800  to Srgb(0x332f38),
                900  to Srgb(0x1d1a22),
                1000 to Srgb(0x000000),
            )

            override val accent1 = mapOf(
                0    to Srgb(0xffffff),
                10   to Srgb(0xfffbfd),
                50   to Srgb(0xf8edff),
                100  to Srgb(0xebdcff),
                200  to Srgb(0xd4bbff),
                300  to Srgb(0xba9cf6),
                400  to Srgb(0x9f81d9),
                500  to Srgb(0x8366bc),
                600  to Srgb(0x6b4fa2),
                700  to Srgb(0x523688),
                800  to Srgb(0x3b1d71),
                900  to Srgb(0x24005a),
                1000 to Srgb(0x000000),
            )

            override val accent2 = mapOf(
                0    to Srgb(0xffffff),
                10   to Srgb(0xfffbfd),
                50   to Srgb(0xf8edff),
                100  to Srgb(0xe9def8),
                200  to Srgb(0xcdc2db),
                300  to Srgb(0xb1a7bf),
                400  to Srgb(0x968da4),
                500  to Srgb(0x7b7289),
                600  to Srgb(0x635b70),
                700  to Srgb(0x4b4358),
                800  to Srgb(0x342d41),
                900  to Srgb(0x1f182b),
                1000 to Srgb(0x000000),
            )

            override val accent3 = mapOf(
                0    to Srgb(0xffffff),
                10   to Srgb(0xfffbfa),
                50   to Srgb(0xffecf1),
                100  to Srgb(0xffd9e4),
                200  to Srgb(0xfcb2c8),
                300  to Srgb(0xde97ad),
                400  to Srgb(0xc07d92),
                500  to Srgb(0xa26377),
                600  to Srgb(0x874c60),
                700  to Srgb(0x6c3548),
                800  to Srgb(0x511f32),
                900  to Srgb(0x370b1d),
                1000 to Srgb(0x000000),
            )

        }

        object MonetGreen : ColorScheme() {
            override val neutral1 = mapOf(
                0    to Srgb(0xffffff),
                10   to Srgb(0xfbfdf7),
                50   to Srgb(0xf0f2ec),
                100  to Srgb(0xe2e3de),
                200  to Srgb(0xc6c7c3),
                300  to Srgb(0xaaaca7),
                400  to Srgb(0x8f918d),
                500  to Srgb(0x747772),
                600  to Srgb(0x5c5f5b),
                700  to Srgb(0x454744),
                800  to Srgb(0x2f312e),
                900  to Srgb(0x1a1c1a),
                1000 to Srgb(0x000000),
            )

            override val neutral2 = mapOf(
                0    to Srgb(0xffffff),
                10   to Srgb(0xf6fff4),
                50   to Srgb(0xebf3e9),
                100  to Srgb(0xdce5da),
                200  to Srgb(0xc0c9bf),
                300  to Srgb(0xa5ada4),
                400  to Srgb(0x8a938a),
                500  to Srgb(0x707870),
                600  to Srgb(0x586159),
                700  to Srgb(0x414941),
                800  to Srgb(0x2b322c),
                900  to Srgb(0x161d17),
                1000 to Srgb(0x000000),
            )

            override val accent1 = mapOf(
                0    to Srgb(0xffffff),
                10   to Srgb(0xf3fff3),
                50   to Srgb(0xc0ffd1),
                100  to Srgb(0x99f7b5),
                200  to Srgb(0x7dda9a),
                300  to Srgb(0x62be81),
                400  to Srgb(0x46a268),
                500  to Srgb(0x278650),
                600  to Srgb(0x006d3a),
                700  to Srgb(0x005229),
                800  to Srgb(0x00391a),
                900  to Srgb(0x00210c),
                1000 to Srgb(0x000000),
            )

            override val accent2 = mapOf(
                0    to Srgb(0xffffff),
                10   to Srgb(0xf3fff3),
                50   to Srgb(0xe0f6e1),
                100  to Srgb(0xd2e9d4),
                200  to Srgb(0xb7ccb9),
                300  to Srgb(0x9bb19e),
                400  to Srgb(0x819684),
                500  to Srgb(0x677b6a),
                600  to Srgb(0x4f6353),
                700  to Srgb(0x384b3c),
                800  to Srgb(0x223527),
                900  to Srgb(0x0d1f13),
                1000 to Srgb(0x000000),
            )

            override val accent3 = mapOf(
                0    to Srgb(0xffffff),
                10   to Srgb(0xf6fdff),
                50   to Srgb(0xd5f6ff),
                100  to Srgb(0xabedfe),
                200  to Srgb(0x8fd0e2),
                300  to Srgb(0x74b5c5),
                400  to Srgb(0x589aaa),
                500  to Srgb(0x3b7f8e),
                600  to Srgb(0x1e6776),
                700  to Srgb(0x004e5c),
                800  to Srgb(0x003641),
                900  to Srgb(0x001f26),
                1000 to Srgb(0x000000),
            )

        }

        object MonetOrange : ColorScheme() {
            override val neutral1 = mapOf(
                0    to Srgb(0xffffff),
                10   to Srgb(0xfffbf9),
                50   to Srgb(0xfaeee7),
                100  to Srgb(0xebe0d9),
                200  to Srgb(0xcfc5be),
                300  to Srgb(0xb3aaa3),
                400  to Srgb(0x978f89),
                500  to Srgb(0x7d746f),
                600  to Srgb(0x655d58),
                700  to Srgb(0x4c4540),
                800  to Srgb(0x352f2b),
                900  to Srgb(0x201b16),
                1000 to Srgb(0x000000),
            )

            override val neutral2 = mapOf(
                0    to Srgb(0xffffff),
                10   to Srgb(0xfffbf9),
                50   to Srgb(0xffeddf),
                100  to Srgb(0xf2dfd1),
                200  to Srgb(0xd5c4b6),
                300  to Srgb(0xb9a89b),
                400  to Srgb(0x9e8e81),
                500  to Srgb(0x827368),
                600  to Srgb(0x695c50),
                700  to Srgb(0x51443a),
                800  to Srgb(0x392e25),
                900  to Srgb(0x231a11),
                1000 to Srgb(0x000000),
            )

            override val accent1 = mapOf(
                0    to Srgb(0xffffff),
                10   to Srgb(0xfffbf9),
                50   to Srgb(0xffeedf),
                100  to Srgb(0xffdcbb),
                200  to Srgb(0xffb86e),
                300  to Srgb(0xeb983e),
                400  to Srgb(0xcb7f26),
                500  to Srgb(0xab6505),
                600  to Srgb(0x8c5000),
                700  to Srgb(0x6a3b00),
                800  to Srgb(0x4b2800),
                900  to Srgb(0x2d1600),
                1000 to Srgb(0x000000),
            )

            override val accent2 = mapOf(
                0    to Srgb(0xffffff),
                10   to Srgb(0xfffbf9),
                50   to Srgb(0xffeedf),
                100  to Srgb(0xffdcbf),
                200  to Srgb(0xe1c1a4),
                300  to Srgb(0xc5a68a),
                400  to Srgb(0xa98b71),
                500  to Srgb(0x8c7158),
                600  to Srgb(0x735a42),
                700  to Srgb(0x59422d),
                800  to Srgb(0x402c18),
                900  to Srgb(0x291806),
                1000 to Srgb(0x000000),
            )

            override val accent3 = mapOf(
                0    to Srgb(0xffffff),
                10   to Srgb(0xfbffdc),
                50   to Srgb(0xe7f9b0),
                100  to Srgb(0xd9eaa3),
                200  to Srgb(0xbdce89),
                300  to Srgb(0xa2b271),
                400  to Srgb(0x889759),
                500  to Srgb(0x6d7c41),
                600  to Srgb(0x56642b),
                700  to Srgb(0x3e4c15),
                800  to Srgb(0x283501),
                900  to Srgb(0x161f00),
                1000 to Srgb(0x000000),
            )

        }

        object MonetTeal : ColorScheme() {
            override val neutral1 = mapOf(
                0    to Srgb(0xffffff),
                10   to Srgb(0xfafdfa),
                50   to Srgb(0xeff2ef),
                100  to Srgb(0xe0e3e1),
                200  to Srgb(0xc4c7c5),
                300  to Srgb(0xa9acaa),
                400  to Srgb(0x8e9190),
                500  to Srgb(0x737775),
                600  to Srgb(0x5b5f5e),
                700  to Srgb(0x444746),
                800  to Srgb(0x2e3130),
                900  to Srgb(0x191c1b),
                1000 to Srgb(0x000000),
            )

            override val neutral2 = mapOf(
                0    to Srgb(0xffffff),
                10   to Srgb(0xf4fefb),
                50   to Srgb(0xe9f3ef),
                100  to Srgb(0xdae5e1),
                200  to Srgb(0xbec9c5),
                300  to Srgb(0xa3aeaa),
                400  to Srgb(0x899390),
                500  to Srgb(0x6e7876),
                600  to Srgb(0x57605e),
                700  to Srgb(0x3f4946),
                800  to Srgb(0x293230),
                900  to Srgb(0x141d1c),
                1000 to Srgb(0x000000),
            )

            override val accent1 = mapOf(
                0    to Srgb(0xffffff),
                10   to Srgb(0xf1fffc),
                50   to Srgb(0xb3fff3),
                100  to Srgb(0x74f8e4),
                200  to Srgb(0x53dbc8),
                300  to Srgb(0x2dbfad),
                400  to Srgb(0x00a392),
                500  to Srgb(0x008576),
                600  to Srgb(0x006b5f),
                700  to Srgb(0x005047),
                800  to Srgb(0x003730),
                900  to Srgb(0x00201b),
                1000 to Srgb(0x000000),
            )

            override val accent2 = mapOf(
                0    to Srgb(0xffffff),
                10   to Srgb(0xf1fffc),
                50   to Srgb(0xdaf7f0),
                100  to Srgb(0xcde8e2),
                200  to Srgb(0xb1ccc6),
                300  to Srgb(0x96b1ab),
                400  to Srgb(0x7c9691),
                500  to Srgb(0x627b76),
                600  to Srgb(0x4a635f),
                700  to Srgb(0x334b47),
                800  to Srgb(0x1c3530),
                900  to Srgb(0x05201c),
                1000 to Srgb(0x000000),
            )

            override val accent3 = mapOf(
                0    to Srgb(0xffffff),
                10   to Srgb(0xfbfcff),
                50   to Srgb(0xe5f2ff),
                100  to Srgb(0xcbe6ff),
                200  to Srgb(0xa0cbf2),
                300  to Srgb(0x84b0d5),
                400  to Srgb(0x6a95ba),
                500  to Srgb(0x4f7a9e),
                600  to Srgb(0x366285),
                700  to Srgb(0x194a6b),
                800  to Srgb(0x003351),
                900  to Srgb(0x001d31),
                1000 to Srgb(0x000000),
            )

        }
    }
}
